name: Pytest

on:
  push:
    branches:
      - main  # replace with your default branch if it's not "main"
  pull_request:
    branches:
      - main  # replace with your default branch if it's not "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # or any other version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install your_package_name  # replace with the actual name or path to your package

    - name: Run Pytest
      run: |
        pytest
